### PR TITLE
add methods to convert entity data to jhipster format

### PR DESCRIPTION
**Pull request by deepu105**
@MathieuAA 

I have copied some stuff from JHUML here so that JDL can be used independently for all JDL related tasks, I guess this would result in some code duplication even once all the JDL related stuff are removed from JHUML. But IMO I would prefer code duplication rather than a broken sub generator in the main generator.

I haven't tested this yet. Let me know if you are ok with this approach and if OK then ill test and fine tune this. I haven't done anything for the scheduler yet as I dont see why any of it is required now.

Some of the copied code can be eliminated if we follow a simpler style (without inheritance and stuff) but anyway I guess you might have had some good reason to do those that way so I kept it as it is. Please take a look

cc @jdubois

### CODE REVIEW

**Comment by MathieuAA** [comment]
Hi Deepu, you shouldn't have added the data classes... another branch is in development to add much better data holders than JUML (that are better suited too for the project). I don't think I'll have time to check before the evening.

**Comment by deepu105** [comment]
Its ok just check when you have time.

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I didnt see the other branch earlier. The new core classes looks much better, when you have time see if that can be adapted for this as well

**Comment by MathieuAA** [comment]
Will do!

**Comment by deepu105** [comment]
Thanks man, we have to bring both the sub generator and JHUML import jdl feature to same level of support soon to avoid the feature not working issues being opened frequently.

**Comment by MathieuAA** [comment]
After a *quick* (ahem) review:
  - ...Data (ClassData, AssociationData, ParsedData) as they are more related to XMI than JDL and the JDL will soon have a much better version of data holding classes;
  - The helpers' right place is a problem, as much as everything that neither this project nor JUML should have had in the first place. I won't move them here, but I will remove them from JUML (as in completely). I still want a common project, or this project to be renamed to be some sort of common project;
  - The EntitiesCreator will be renamed EntityCreator (in JUML) and will be split into more objects. Some of these don't belong to either JDL or JUML, that's the same thing as my previous point... There's a branch [here](https://github.com/jhipster/jhipster-uml/tree/new_entity_creator) for the new version which will be easier to maintain and split;
  - The JDLParser will be removed from JUML and JUML will use the core objects from the JDL project;
  - The types and the cardinalities don't belong in JUML and JDL. Same point as previous...

I may have forgotten some things, but I agree with you 100%. 
Unfortunately with my holidays I couldn't finish what I wanted in time, I'll try to finish some things by the end of the week.
One of the things I will test is a project renaming... If it works, I'll ask Julien to rename this project so that we can put whatever you and I want here. If not, then I'll make a common project. Both situations would require to list everything to refactor (you just did that for JUML, and I think that should be all...).

**Comment by deepu105** [comment]
May be lets rename this project to `jhipster-utils` or `jhipster-core` or
`jhipster-commons`, as the current project which is wrapper around peg
parser alone doesn't do any good.

I have renamed projects in the past and it works fine. You have to publish
it as new npm package though but that should be fine as its used only
internally by us anyways.

**Comment by MathieuAA** [comment]
Nice! Then let's. @jdubois can you do this when you have a few minutes to spare? 
The next step would be to create a branch where every migrated stuff is here and where the folder structure is good enough.

**Comment by jdubois** [comment]
I can rename this project with the name you want, but something like "jhipster-core" is too generic for me. I like "jhipster-domain-language" as at least you know what it's about.

**Comment by deepu105** [comment]
The problem is it needs to do more than just JDL stuff like host common
functionality for import-jdl sub gen, JHUML etc. So "jhipster-domain-language"
might be a little misleading. What about `jhipster-commons` or
`jhipster-util` ?

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
They are also both very generic and don't tell what the project is about. Isn't it all related to JDL?

**Comment by MathieuAA** [comment]
Not really. The JDL part would actually not be the most useful, but it would stay "common" (the subgen, JUML, the studio would be using the JDL). 

The most useful stuff would be taken from JUML or JHipster if some notions like types or constraints are included.

Le 23 mai 2016 12:06:57 GMT+02:00, Julien Dubois <notifications@github.com> a écrit :
>They are also both very generic and don't tell what the project is
>about. Isn't it all related to JDL?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/pull/23#issuecomment-220939580

-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
OK, "jhipster-core" if you want, as it's the core for the other projects -> are you OK if I rename this project?

**Comment by MathieuAA** [comment]
Thanks Julien

**Comment by deepu105** [comment]
@jdubois yes `jhipster-core` would be good. Plz rename

**Comment by deepu105** [comment]
@MathieuAA were you able to complete the new core objects part?

**Comment by MathieuAA** [comment]
Almost, the final object is close to completion. After that, the branch will be merged into master, and the entitycreator will be moved here.

**Comment by deepu105** [comment]
Thanks man :) we are getting more and more [issues ](https://github.com/jhipster/generator-jhipster/issues/3683#issuecomment-223901785) on this so we need to close this with high priority. Let me know if you need any help from me.

**Comment by MathieuAA** [comment]
I agree, this task is blocking the others and I'm fed up =/ After this branch is merged, a lot of issues should disappear. I may be able to finish this today or tomorrow.

**Comment by deepu105** [comment]
@MathieuAA I guess you have completed the core objects migration do you want me to rework this PR to add the entity converter and stuff or do you want to do it yourself. will be happy if you can do it as i'm busy with the Angular2 migration already, if not I can try to find some time for this

**Comment by MathieuAA** [comment]
Please do! I'm quite busy myself... writing a parser for another editor was more tricky than I remember

**Comment by deepu105** [comment]
Im not gonna write any new parsers, I just want to port the common code
from JHUML to here so that we can use it on JHUML and the import sub gen to
create entity fromJDL


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
I know, but I am =)

Le 18 juin 2016 17:08:47 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>Im not gonna write any new parsers, I just want to port the common code
>from JHUML to here so that we can use it on JHUML and the import sub
>gen to
>create entity fromJDL
>
>
>Thanks & Regards,
>Deepu
>
>On Sat, Jun 18, 2016 at 11:02 PM, Mathieu ABOU-AICHI <
>notifications@github.com> wrote:
>
>> Please do! I'm quite busy myself... writing a parser for another
>editor
>> was more tricky than I remember
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>>
><https://github.com/jhipster/jhipster-domain-language/pull/23#issuecomment-226946963>,
>> or mute the thread
>>
><https://github.com/notifications/unsubscribe/ABDlF58Tw79jyhA_XZ37VDYz03_z0vHqks5qNAiNgaJpZM4IhCl1>
>> .
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/pull/23#issuecomment-226947270

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
I have started work on the converter in the `dslparser` branch. I have fixed all the issues in the DSL prser, it now parses and outputs properly, need to add some tests. hence closing this

**Comment by deepu105** [comment]
Ill try to finish it today or tomorrow as I find time

**Pull request closed without merging**
