### PR TITLE
added JDLDirective to parser to exclude rendering options set via #

### PR DESCRIPTION
**Pull request by NilsWild**
added JDLDirective to parser to exclude rendering options set via # in jdl editor

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'd rather have the JDLStudio remove everything starting with the # character so that we don't mix a char with no relation whatsoever with the JDL and JHipster... I'll think about it. I may come up with a filter.

Le 17 juin 2016 15:08:04 GMT+02:00, NilsWild <notifications@github.com> a écrit :
>added JDLDirective to parser to exclude rendering options set via # in
>jdl editor
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/jhipster/jhipster-domain-language/pull/29
>
>-- Commit Summary --
>
>* added JDLDirective to parser to exclude rendering options set via #
>in jdl editor
>
>-- File Changes --
>
>    M lib/dsl/grammar.txt (6)
>    M lib/dsl/pegjs_parser.js (381)
>
>-- Patch Links --
>
>https://github.com/jhipster/jhipster-domain-language/pull/29.patch
>https://github.com/jhipster/jhipster-domain-language/pull/29.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/pull/29

-- 
Mathieu ABOU-AICHI

**Comment by NilsWild** [comment]
well if JDLStudio does remove those directives before saving i would loose my rendering settings when saving my jdl file. Don't think that's a desireable behavior.

But maybe i got you wrong in what you mean by: 

> I'd rather have the JDLStudio remove everything starting with the # character

**Comment by MathieuAA** [comment]
Fair enough. A filter will have to be made so that you don't lose any information. Can you do it? 

Le 17 juin 2016 17:48:47 GMT+02:00, NilsWild <notifications@github.com> a écrit :
>well if JDLStudio does remove those directives before saving i would
>loose my rendering settings when saving my jdl file. Don't think that's
>a desireable behavior.
>
>But maybe i got you wrong in what you mean by: 
>
>> I'd rather have the JDLStudio remove everything starting with the #
>character 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/pull/29#issuecomment-226806130

-- 
Mathieu ABOU-AICHI

**Comment by NilsWild** [comment]
That's what i intended to do. My PR basically adds a Filter to the parser, so that anythink starting with # is treated as an JDLDirective which is treated simmilar to a JDLComment.

I'm not sure what you mean by a Filter. My PR is a Filter basically.

**Comment by MathieuAA** [comment]
No, I meant before the parsing... But either way works. My solution allows me to alter the file if I want to, or have special directives.

Le 17 juin 2016 18:35:39 GMT+02:00, NilsWild <notifications@github.com> a écrit :
>That's what i intended to do. My PR basically adds a Filter to the
>parser, so that anythink starting with # is treated as an JDLDirective
>which is treated simmilar to a JDLComment.
>
>I'm not sure what you mean by a Filter. My PR is a Filter basically.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/pull/29#issuecomment-226817981

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
@NilsWild thank you :+1:

**Pull request merged**
